[ScalabilitySettings]
; M4 Pro Custom Scalability Preset

[ViewDistanceQuality@2]
r.SkeletalMeshLODBias=1
r.ViewDistanceScale=0.8

[AntiAliasingQuality@2]
r.PostProcessAAQuality=3
r.MSAA.CompositingSampleCount=2

[ShadowQuality@2]
r.Shadow.Virtual.Enable=1
r.Shadow.Virtual.ResolutionLodBiasLocal=1.0
r.Shadow.RadiusThreshold=0.04
r.Shadow.DistanceScale=0.8
r.Shadow.CSM.TransitionScale=0.8
r.Shadow.MaxCSMResolution=1024
r.Shadow.MaxResolution=1024

[GlobalIlluminationQuality@2]
r.Lumen.DiffuseIndirect.Allow=1
r.Lumen.ScreenProbeGather.DownsampleFactor=32
r.Lumen.ScreenProbeGather.TracingOctahedronResolution=4

[ReflectionQuality@2]
r.Lumen.Reflections.Allow=1
r.Lumen.Reflections.DownsampleFactor=2
r.SSR.Quality=1

[PostProcessQuality@2]
r.MotionBlurQuality=2
r.AmbientOcclusionMipLevelFactor=0.5
r.AmbientOcclusionMaxQuality=60
r.AmbientOcclusionLevels=1
r.AmbientOcclusionRadiusScale=1.2
r.DepthOfFieldQuality=1
r.RenderTargetPoolMin=400
r.LensFlareQuality=0
r.SceneColorFringeQuality=0
r.BloomQuality=3
r.FastBlurThreshold=3
r.Tonemapper.GrainQuantization=0

[TextureQuality@2]
r.Streaming.MipBias=0.5
r.Streaming.AmortizeCPUToGPUCopy=1
r.Streaming.MaxNumTexturesToStreamPerFrame=2
r.Streaming.Boost=0
r.MaxAnisotropy=4
r.VT.MaxAnisotropy=4
r.Streaming.PoolSize=1500

[EffectsQuality@2]
r.TranslucencyLightingVolumeDim=32
r.RefractionQuality=1
r.SceneColorFormat=3
r.DetailMode=1
r.MaterialQualityLevel=1
r.SSS.Scale=0.75
r.SSS.SampleSet=0
r.EmitterSpawnRateScale=0.8
r.ParticleLightQuality=1

[FoliageQuality@2]
foliage.DensityScale=0.8
grass.DensityScale=0.7
foliage.LODDistanceScale=0.8

[ShadingQuality@2]
r.HairStrands.SkyLighting.IntegrationType=1
r.HairStrands.Visibility.MSAA.SamplePerPixel=2
